/*
"name": "Adult Blue Dracolich",
"size": "Huge",
"type": "undead",
"subtype": "",
"alignment": "lawful evil",
"armor_class": 19,
"hit_points": 225,
"hit_dice": "18d12",
"speed": "40 ft., burrow 30 ft., fly 80 ft.",
"strength": 25,
"dexterity": 10,
"constitution": 23,
"intelligence": 16,
"wisdom": 15,
"charisma": 19,
"perception": 12,
"damage_vulnerabilities": "",
"damage_resistances": "necrotic",
"damage_immunities": "lightning, poison",
"condition_immunities": "charmed, exhaustion, frightened, paralyzed, poisoned",
"senses": "blindsight 60 ft., darkvision 120 ft., passive Perception 22",
"languages": "Common, Draconic",
"challenge_rating": "17",
*/
